language: java
jdk:
  - openjdk7
deploy:
  provider: heroku
  api_key:
    secure: ${API_KEY}
  app: oms-apps1
  on:
    repo: orest77/oms-heroku

services: 
  - mariadb
before_script:
  - mysql -u root -e 'CREATE DATABASE oms;'
  - mysql -u root -e "CREATE USER 'user_db'@'localhost' IDENTIFIED BY 'SUPER123pass';"
  - mysql -u root -e "GRANT ALL ON oms.* TO 'user_db'@'localhost';"


